### ISSUE TITLE
PySimpleGUI...

### ISSUE THREAD

**Issue by PySimpleGUI** [Mavireck/Python-Screen-Stack-Manager#1]
Hi!

Glad you found PySimpleGUI to be inspirational!

**Comment by Mavireck** [comment]
I do not know how you came to notice this repo, but I must say I do truly admire PySimpleGUI's simplicity, and it truly influenced the way I wrote this code!

**Comment by PySimpleGUI** [comment]
That great to hear!  

I found you by trying to keep my finger on the pulse of PySimpleGUI. I review projects every day that either use it directly or indirectly was you did.  It helps inform the direction of the project.  

Getting suggestions via Issues and reading things like Reddit posts only provide me data from a vocal minority of people.  I find stuff by going out and actively looking for it.
